package europa.edit.pages;

import lombok.experimental.UtilityClass;
import org.openqa.selenium.By;

@UtilityClass
public class AnnotationPage {
    public static final By SORT_BY_BUTTON = By.xpath("//button[@class='top-bar__btn dropdown-toggle']");
    public static final By SORT_BY_DROP_DOWN_LIST = By.xpath("//ul[@class='dropdown-menu pull-right']//li//a");
    public static final By SORT_BY_DROP_DOWN_LIST_SELECTED_OPTION = By.xpath("//ul[@class='dropdown-menu pull-right']//li//span[@class='dropdown-menu-radio is-selected']//following-sibling::a");
    public static final By COMMENT_RICH_TEXTAREA = By.xpath("//*[contains(@class,'is-comment')]//div[@ng-show='vm.showEditor()' and not(@class='ng-hide')]//div[contains(@id,'cke_editor')]");
    public static final By COMMENT_HIGHLIGHT_SUGGESTION_RICH_TEXTAREA_PARAGRAPH = By.xpath("//*[contains(@class,'cke_editable_themed')]/p");
    public static final By COMMENT_TEXTBOX_DELETE_BUTTON = By.xpath("//*[contains(@class,'thread-list__card is-comment')]//i[@class='h-icon-annotation-delete btn-icon']");
    public static final By COMMENT_ARROW_DOWN_BUTTON = By.xpath("//div[contains(@class,'is-comment')]//button[@class='dropdown-menu-btn__dropdown-arrow']");
    public static final By COMMENT_PUBLISH_BUTTON = By.xpath("//div[contains(@class,'is-comment')]//button[@class='dropdown-menu-btn__btn ng-binding']");
    public static final By COMMENT_TEXTAREA_PARAGRAPH_INNERTEXT = By.xpath("//div[contains(@class,'is-comment')]//div[@class='markdown-body js-markdown-preview has-content']/p");
    public static final By SELECTED_COMMENT_BOX = By.xpath("//div[contains(@class,'is-comment is-annotation-selected')]");
    public static final By SELECTED_COMMENT_BOX_PARAGRAPH = By.xpath("//div[contains(@class,'is-comment is-annotation-selected')]//div[@class='markdown-body js-markdown-preview has-content']/p");
    public static final By SELECTED_COMMENT_BOX_EDIT_ICON = By.xpath("//*[contains(@class,'is-comment is-annotation-selected')]//i[@class='h-icon-annotation-edit btn-icon']");
    public static final By SELECTED_COMMENT_BOX_REPLY_ICON = By.xpath("//*[contains(@class,'is-comment is-annotation-selected')]//i[@class='h-icon-annotation-reply btn-icon']");
    public static final By SELECTED_COMMENT_BOX_ADD_REPLY_BUTTON = By.xpath("//*[contains(@class,'is-comment is-annotation-selected')]//span[text()='Add reply']");
    public static final By SELECTED_COMMENT_BOX_HIDE_REPLY_BUTTON = By.xpath("//*[contains(@class,'is-comment is-annotation-selected')]//span[text()='Hide reply']");
    public static final By SELECTED_COMMENT_BOX_ALL_REPLY_LIST_PARAGRAPH_LIST = By.xpath("//*[contains(@class,'is-comment is-annotation-selected')]//ul//li[@class='ng-scope']//section[@class='annotation-body']//div[@class='markdown-body js-markdown-preview has-content']//p");
    public static final By SELECTED_COMMENT_BOX_CANCEL_BUTTON = By.xpath("//*[contains(@class,'is-comment is-annotation-selected')]//button[@class='publish-annotation-cancel-btn btn-clean']");
    public static final By SELECTED_SUGGESTION_BOX = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]");
    public static final By SELECTED_SUGGESTION_BOX_SHOW_JUSTIFICATION_LINK = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]//span[text()='Show justification']//ancestor::a");
    public static final By SUGGESTION_TEXTAREA = By.xpath("//div[contains(@class,'is-suggestion')]//textarea[not(contains(@class,'ng-hide'))]");
    public static final By SUGGESTION_ARROW_DOWN_BUTTON = By.xpath("//div[contains(@class,'is-suggestion')]//button[@class='dropdown-menu-btn__dropdown-arrow']");
    public static final By SUGGESTION_PUBLISH_BUTTON = By.xpath("//div[contains(@class,'is-suggestion')]//button[@class='dropdown-menu-btn__btn ng-binding']");
    public static final By SUGGESTION_TEXTAREA_PARAGRAPH_INNERTEXT = By.xpath("//div[contains(@class,'is-suggestion')]//div[@class='markdown-body js-markdown-preview has-content']/p");
    public static final By SUGGESTION_ACCEPT_BUTTON = By.xpath("//div[contains(@class,'is-suggestion')]//button[@class='suggestion-merge-action']");
    public static final By SELECTED_SUGGESTION_BOX_ACCEPT_BUTTON = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]//button[@class='suggestion-merge-action']");
    public static final By SUGGESTION_REJECT_BUTTON = By.xpath("//div[contains(@class,'is-suggestion')]//button[@class='publish-annotation-cancel-btn btn-clean']");
    public static final By SELECTED_SUGGESTION_BOX_REJECT_BUTTON = By.xpath("//div[contains(@class,'is-suggestion is-annotation-selected')]//button[@class='publish-annotation-cancel-btn btn-clean']");
    public static final By SELECTED_SUGGESTION_BOX_ADD_JUSTIFICATION_LINK = By.xpath("//*[contains(@class,'is-suggestion')]//span[text()='Add justification']//parent::a");
    public static final By SELECTED_SUGGESTION_BOX_HIDE_JUSTIFICATION_LINK = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]//span[text()='Hide justification']//parent::a");
    public static final By SELECTED_SUGGESTION_BOX_JUSTIFICATION_PARAGRAPH_LIST = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]//div[@class='markdown-body js-markdown-preview']//p");
    public static final By SELECTED_SUGGESTION_BOX_REPLY_ICON = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]//i[@class='h-icon-annotation-reply btn-icon']");
    public static final By SELECTED_SUGGESTION_BOX_ADD_REPLY_BUTTON = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]//span[text()='Add reply']");
    public static final By SELECTED_SUGGESTION_BOX_ALL_REPLY_LIST_PARAGRAPH_LIST = By.xpath("//*[contains(@class,'is-suggestion is-annotation-selected')]//ul//li[@class='ng-scope']//section[@class='annotation-body']//div[@class='markdown-body js-markdown-preview has-content']//p");
    public static final By HIGHLIGHT_TEXTBOX = By.cssSelector(".is-highlight #annotation-wrapper");
    public static final By HIGHLIGHT_RICH_TEXTAREA = By.xpath("//*[contains(@class,'is-highlight')]//div[@ng-show='vm.showEditor()' and not(@class='ng-hide')]//div[contains(@id,'cke_editor')]");
    public static final By HIGHLIGHT_TEXTBOX_EDIT_BUTTON = By.cssSelector(".is-highlight i.h-icon-annotation-edit");
    public static final By HIGHLIGHT_TEXTBOX_DELETE_BUTTON = By.xpath("//*[contains(@class,'thread-list__card is-highlight')]//i[@class='h-icon-annotation-delete btn-icon']");
    public static final By HIGHLIGHT_TEXTAREA = By.xpath("//div[contains(@class,'is-highlight')]//textarea");
    public static final By HIGHLIGHT_ARROW_DOWN_BUTTON = By.xpath("//div[contains(@class,'is-highlight')]//button[@class='dropdown-menu-btn__dropdown-arrow']");
    public static final By HIGHLIGHT_PUBLISH_BUTTON = By.xpath("//div[contains(@class,'is-highlight')]//button[@class='dropdown-menu-btn__btn ng-binding']");
    public static final By HIGHLIGHT_TEXTAREA_PARAGRAPH_INNERTEXT = By.xpath("//div[contains(@class,'is-highlight')]//div[@class='markdown-body js-markdown-preview has-content']/p");
    public static final By PUBLISH_ANNOTATION_UL_LI_A = By.cssSelector(".publish-annotation-btn__dropdown-menu ul li a");
    public static final By ANNOTATION_COMMENT_PARAGRAPH = By.xpath("//*[@class='thread-list__card is-comment']//*[contains(@class,'has-content')]//p");
    public static final By ANNOTATION_SUGGESTION_CONTENT_NEW = By.xpath("//*[@class='thread-list__card is-suggestion']//*[contains(@class,'has-content')]//span[@class='leos-content-new']");
    public static final By ANNOTATION_COUNT = By.cssSelector(".selection-tabs__count");
    public static final By ORPHANS_COUNT = By.xpath("//selection-tabs//a[contains(text(),'Orphans')]//span");
    public static final By SUGGESTION_SUCCESSFULLY_MERGED_MESSAGE = By.xpath("//*[text()='Suggestion successfully merged']");
    public static final By REPLY_POST_BTN = By.cssSelector(".is-comment div.dropdown-menu-btn");
    public static final By ANNOTATION_TOOLBAR = By.cssSelector(".annotator-toolbar");
    public static final By SELECTION_PANE = By.cssSelector("selection-pane.ng-scope");
    public static final By LEOS_SELECTION_PANE_LABEL = By.cssSelector(".leos-selection-pane__label");
    public static final By LEOS_SELECTION_PANE_ACTION_LABEL = By.cssSelector(".leos-selection-pane__action-label");
    public static final By LEOS_SELECTION_PANE_BUTTON = By.cssSelector(".leos-selection-pane__grid:nth-child(1) .leos-selection-pane__button");
    public static final By LEOS_SELECTION_PANE_ACTIONS_BUTTON = By.cssSelector(".leos-selection-pane__actions-section button.leos-selection-pane__button");
    public static final By ANNOTATION_UNAVAILABLE_MESSAGE_LABEL = By.cssSelector(".annotation-unavailable-message__label");
    public static final By ANNOTATION_COMMENT = By.cssSelector(".thread-list__card.is-comment");
    public static final By ANNOTATION_SUGGESTION = By.cssSelector(".thread-list__card.is-suggestion");
    public static final By ANNOTATION_ACTION_TREATED_INPUT = By.cssSelector(".annotation-action-treated input");
    public static final By ANNOTATION_ACTION_TREATED_SPAN = By.cssSelector(".annotation-action-treated span");
    public static final By ANNOTATION_COMMENT_MARK_AS_PROCESSED = By.cssSelector(".thread-list__card.is-comment footer .annotation-action-treated span");
    public static final By ANNOTATION_SUGGESTION_MARK_AS_PROCESSED = By.cssSelector(".thread-list__card.is-suggestion footer .annotation-action-treated span");
    public static final String COMMENT_TEXTBOX = "//*[contains(@class,'thread-list__card is-comment')]";
    public static final String SUGGESTION_TEXTBOX = "//*[contains(@class,'thread-list__card is-suggest')]";
    public static final String NG_SHOW_EDITOR = "//div[@ng-show='vm.showEditor()' and not(@class='ng-hide')]";
    public static final String HIGHLIGHT_ANNOTATION = "//*[contains(@class,'is-highlight')]";
    public static final String COMMENT_ANNOTATION = "//*[contains(@class,'is-comment')]";
    public static final String SUGGESTION_ANNOTATION = "//*[contains(@class,'is-suggestion')]";
    public static final String RICH_TEXTAREA_IFRAME = "//*[contains(@class,'cke_wysiwyg_frame')]";
    public static final String THREAD_LIST_CARD_IS_COMMENT = "//div[@class='thread-list__card is-comment']";
    public static final String MARKDOWN_PREVIEW_HAS_CONTENT = "//div[@class='markdown-body js-markdown-preview has-content']";
}

