package europa.edit.pages;

import lombok.experimental.UtilityClass;
import org.openqa.selenium.By;

@UtilityClass
public class LegalActPage {
    public static final By CITATION_LINK = By.xpath("//*[text()='Citations']");
    public static final By CITATION_SECOND_PARAGRAPH = By.xpath("//citation[2]/aknp");
    public static final By LEGAL_ACT_TEXT = By.xpath("//span[text()='Legal Act']");
    public static final By PREAMBLE_TOGGLE_LINK = By.xpath("//*[text()='Preamble']//preceding-sibling::span");
    public static final By RECITALS_TOGGLE_LINK = By.xpath("//*[text()='Recitals']//preceding-sibling::span");
    public static final By CITATIONS_TOGGLE_LINK = By.xpath("//*[text()='Citations']//preceding-sibling::span");
    public static final By CK_EDITOR_WINDOW_1 = By.cssSelector(".cke_browser_webkit");
    public static final By CK_EDITOR_WINDOW_2 = By.cssSelector(".leos-placeholder.cke_editable");
    public static final By CITATION_BEFORE_CKEDITOR = By.xpath("//p//ancestor::div[contains(@class,'cke_editable')]//preceding-sibling::citation");
    public static final By EDIT_FOOTNOTE_WINDOW = By.xpath("//*[text()='Edit Footnote']");
    public static final By FOOTNOTE_WINDOW_TEXTAREA = By.xpath("//textarea[@class='cke_dialog_ui_input_textarea ']");
    public static final By FOOTNOTE_WINDOW_OK_BUTTON = By.xpath("//*[@class='cke_dialog_ui_button' and text()='OK']");
    public static final By TABLE_PROPERTIES_WINDOW = By.xpath("//*[@class='cke_dialog_title' and text()='Table Properties']");
    public static final By TABLE_PROPERTIES_WINDOW_ROWS_INPUT = By.xpath("//label[@class='cke_dialog_ui_labeled_label cke_required' and text()='Rows']//following-sibling::div//input");
    public static final By TABLE_PROPERTIES_WINDOW_COLUMNS_INPUT = By.xpath("//label[@class='cke_dialog_ui_labeled_label cke_required' and text()='Columns']//following-sibling::div//input");
    public static final By TABLE_PROPERTIES_WINDOW_HEADER_SELECT = By.xpath("//*[@class='cke_dialog_ui_labeled_label' and text()='Headers']//following-sibling::div//select[@class='cke_dialog_ui_input_select']");
    public static final By TABLE_PROPERTIES_WINDOW_HEADER_OK_BUTTON = By.xpath("//*[text()='Table Properties']//following-sibling::table//*[@class='cke_dialog_ui_button' and text()='OK']\n");
    public static final By CK_EDTOR_PARAGRAPH_INNERTEXT = By.xpath("//*[contains(@class,cke_editable_inline) and @role='textbox']//p");
    public static final By CK_EDITOR_PARAGRAPH_INNERTEXT_OL_LI = By.xpath("//*[contains(@class,cke_editable_inline) and @role='textbox']//ol//li");
    public static final By CK_EDTOR_HEADING_ORIGIN_EC = By.xpath("//*[contains(@class,cke_editable_inline) and @role='textbox']//*[@class='akn-element-heading' and @data-heading-origin='ec']");
    public static final By CK_EDTOR_LI_INNERTEXT = By.xpath("//*[contains(@class,cke_editable_inline) and @role='textbox']//li");
    public static final By TOGGLE_BAR_IN_LEFT_SIDE = By.xpath("//button[@title='Toggle or Resize Sidebar' and contains(@class,'h-icon-chevron-right')]");
    public static final By TOGGLE_BAR_IN_RIGHT_SIDE = By.xpath("//button[@title='Toggle or Resize Sidebar' and contains(@class,'h-icon-chevron-left')]");
    public static final By TOC_EDIT_BUTON = By.xpath("//img[contains(@src,'toc-edit.png')]");
    public static final By PREAMBLE_FORMULA_AKNP = By.xpath("//preamble/formula[1]/aknp");
    public static final By PREAMBLE_TEXT = By.xpath("//div[text()='Preamble']");
    public static final By VERTICAL_SCROLL_BAR = By.xpath("//*[@id='leosAccordion']//*[@class='v-treegrid-scroller v-treegrid-scroller-vertical']");
    public static final By NAVIGATION_PANE_SAVE_BUTTON = By.xpath("//*[contains(@src,'toc-save')]//ancestor::div[@role='button']");
    public static final By NAVIGATION_PANE_SAVE_AND_CLOSE_BUTTON = By.xpath("//*[contains(@src,'toc-save-close')]//ancestor::div[@role='button']");
    public static final By NAVIGATION_PANE_CANCEL_BUTTON = By.xpath("//*[contains(@src,'toc-cancel')]//ancestor::div[@role='button']");
    public static final By NAVIGATION_ELEMENTS_LIST = By.xpath("//*[text()='Elements']//ancestor::div[contains(@class,'leos-left-slider-panel')]//div[contains(@class,'leos-drag-item')]");
    public static final By LEOS_DRAG_ITEM_LIST = By.cssSelector(".leos-drag-item");
    public static final By NAVIGATION_ELEMENTS_LEFT_SLIDER_PANEL = By.xpath("//*[text()='Elements']//ancestor::div[contains(@class,'leos-left-slider-panel')]");
    public static final By LEGAL_ACT_CONTENT = By.xpath("//*[@id='legalTextLayout']");
    public static final By ACTION_MENU = By.xpath("//div[contains(@class,'v-horizontallayout-leos-viewdoc-docbar')]//span[contains(@class,'leos-actions-menu-selector')]//img[contains(@src,'hamburguer.png')]");
    public static final By ACTIONS_MENU_BAR_POP_UP = By.xpath("//*[@class='v-menubar-popup']//*[contains(@class,'leos-actions-menu')]//span//span");
    public static final By RECITALS_SOFT_NEW = By.xpath("//recital[@class='leos-content-soft-new']");
    public static final By ARTICLES_SOFT_NEW = By.xpath("//article[@class='leos-content-soft-new']");
    public static final By RECENT_CHANGES_SHOW_MORE_BUTTON = By.xpath("//*[text()='Recent changes']"+LegalActPage.ANCESTOR_VERSION_CARD+"//*[contains(@class,'show-versions-button') and @role='button']");
    public static final By EXPORT_BUTTON_ECONSILIUM_WINDOW = By.xpath("//*[text()='Export']");
    public static final By TITLE_ECONSILIUM_WINDOW = By.xpath("//*[text()='Title']//ancestor::tr//textarea");
//    public static final By SAVE_CLOSE_BUTTON_DISABLED = By.xpath("//a[@title='Save Close' and contains(@class,'disabled')]");
//    public static final By SAVE_BUTTON_DISABLED = By.xpath("//a[@title='Save' and contains(@class,'disabled')]");
    public static final By CONFIRM_CANCEL_EDITING = By.xpath("//*[text()='Confirm cancel editing.']");
    public static final By OK_BUTTON = By.xpath("//*[text()='OK']");
    public static final By RECITAL_NEW = By.xpath("//recital[contains(@id,'imp')]");
    public static final By ARTICLE_NEW = By.xpath("//article[contains(@id,'imp')]");
    public static final By SHOW_ALL_ACTIONS_INSERT_BEFORE = By.xpath("//*[@data-widget-type='insert.before' and @style='display: inline-block;']");
    public static final By SHOW_ALL_ACTIONS_INSERT_AFTER = By.xpath("//*[@data-widget-type='insert.after' and @style='transform: rotate(180deg); display: inline-block;']");
    public static final By SHOW_ALL_ACTIONS_EDIT = By.xpath("//*[@data-widget-type='edit' and @style='display: inline-block;']");
    public static final By SHOW_ALL_ACTIONS_DELETE = By.xpath("//*[@data-widget-type='delete' and @style='display: inline-block;']");
    public static final By COMPARE_VERSIONS_BUTTON = By.id("compareModeButton");
    public static final By SEARCH_BUTTON = By.id("searchButton");
    public static final By SHOW_LESS_BUTTON = By.xpath("//*[@id='showVersionsBlock']//*[text()='Show less']");
    public static final By NAVIGATION_PANE_TOGGLE_LINK = By.cssSelector(".v-accordion-item-first span.v-icon");
    public static final By VERSIONS_PANE_TOGGLE_LINK = By.xpath("//*[text()='Versions pane']//ancestor::div[@class='v-accordion-item' and @tabindex='-1']");
    public static final By SAVE_BUTTON_SAVE_THIS_VERSION_WINDOW = By.xpath("//*[text()='Save']//ancestor::div[@role='button']");
    public static final By TITLE_INPUT_SAVE_THIS_VERSION_WINDOW = By.xpath("//input[@placeholder='e.g.: this is my title']");
    public static final By SAVE_THIS_VERSION_ACTIONS_MENU_ITEM = By.xpath("//*[text()='Save this version']");
    public static final By NO_CHANGES_AFTER_LAST_VERSION = By.xpath("//*[text()='Recent changes']"+LegalActPage.ANCESTOR_VERSION_CARD+"//*[text()='No changes after last version']");
    public static final By UN_DELETE_BUTTON = By.xpath("//span[text()='Undelete']");
    public static final By VIEW_THIS_VERSION_MENU = By.xpath("//*[@class='v-menubar-popup']//*[@class='popupContent']//*[contains(@class,'leos-actions-menu')]//span[@class='v-menubar-menuitem-caption']");
    public static final By RECITALS_TEXT = By.xpath("//*[text()='Recitals']");
    public static final By SELECTED_ELEMENT_TYPE_INPUT = By.xpath("//*[text()='Type']//ancestor::tr//input");
    public static final By SELECTED_ELEMENT_NUMBER_INPUT = By.xpath("//*[text()='Number']//ancestor::tr//input");
    public static final By SELECTED_ELEMENT_HEADING_INPUT = By.xpath("//*[text()='Heading']//ancestor::tr//input");
    public static final By SELECTED_ELEMENT_PARAGRAPH_NUMBERING_NUMBERED_INPUT = By.xpath("//*[text()='Paragraph Numbering']//ancestor::div[@class='v-widget v-has-caption v-caption-on-top']//label[text()='Numbered']//ancestor::span//input");
    public static final By SELECTED_ELEMENT_PARAGRAPH_NUMBERING_UNNUMBERED_INPUT = By.xpath("//*[text()='Paragraph Numbering']//ancestor::div[@class='v-widget v-has-caption v-caption-on-top']//label[text()='Unnumbered']//ancestor::span//input");
    public static final By SELECTED_ELEMENT_PARAGRAPH_NUMBERING_LABEL_LIST = By.xpath("//*[text()='Paragraph Numbering']//ancestor::div[@class='v-widget v-has-caption v-caption-on-top']//label");
    public static final By SELECTED_ELEMENT_DELETE_BUTTON = By.xpath("(//*[contains(@class,'leos-toc-editor')])[1]//*[text()='Delete']");
    public static final By SELECTED_ELEMENT_CLOSE_BUTTON = By.xpath("//*[text()='Selected element']//ancestor::div[contains(@class,'leos-slider-toolbar')][1]//*[@role='button']");
    public static final By OK_BUTTON_INTERNAL_REFERENCE_WINDOW = By.cssSelector(".cke_dialog_ui_button_ok");
    public static final By AUTHORIAL_NOTE_TABLE = By.cssSelector(".leos-authnote-table .leos-authnote marker");
    public static final By LEOS_DOC_TITLE = By.cssSelector(".leos-docview-doctitle");
    public static final String HYPOTHESIS_HIGHLIGHT = "//hypothesis-highlight[contains(@class,'annotator-hl')]";
    public static final String HYPOTHESIS_HIGHLIGHT_SELECTED = "//hypothesis-highlight[@class='annotator-hl annotator-hl-selected']";
    public static final String HYPOTHESIS_HIGHLIGHT_FOCUSED = "//hypothesis-highlight[@class='annotator-hl annotator-hl-focused']";
    public static final String CITATION = "//citation";
    public static final String RECITAL = "//recital";
    public static final String POINT = "//point";
    public static final String PARAGRAPH = "//paragraph";
    public static final String SUBPARAGRAPH = "//subparagraph";
    public static final String NAVIGATION_MENU_ITEM_CHECKED = "//parent::span[@aria-checked='true']";
    public static final String ACTIONS_SUB_MENU_ITEM = "//*[contains(@class,'leos-actions-sub-menu-item')]";
    public static final String RECENT_CHANGES_TEXT = "//*[text()='Recent changes']";
    public static final String CK_EDITABLE_INLINE = "//*[contains(@class,'cke_editable_inline')]";
    public static final String SELECTED_ELEMENT_TEXT = "//*[text()='Selected element']";
    public static final String BILL = "//bill";
    public static final String ARTICLE = "//article";
    public static final String CITATIONS = "//citations";
    public static final String AKNP = "//aknp";
    public static final String AKNBODY = "//aknbody";
    public static final String RECITALS = "//recitals";
    public static final String CONTENT = "//content";
    public static final String LI = "//li";
    public static final String LIST = "//list";
    public static final String HEADING = "//heading";
    public static final String PREFACE = "//preface";
    public static final String DOC_PURPOSE = "//docpurpose";
    public static final String SPAN = "//span";
    public static final String NUM = "//num";
    public static final String NUM_SINGLE_SLASH = "/num";
    public static final String MREF = "//mref";
    public static final String REF = "//ref";
    public static final String LIST_SINGLE_SLASH = "/list";
    public static final String POINT_SINGLE_SLASH = "/point";
    public static final String ALINEA_SINGLE_SLASH = "/alinea";
    public static final String CONTENT_SINGLE_SLASH = "/content";
    public static final String AKNP_SINGLE_SLASH = "/aknp";
    public static final String SPAN_SINGLE_SLASH = "/span";
    public static final String CKE_DIALOG_CONTENTS = "//table[@class='cke_dialog_contents']";
    public static final String CKE_DIALOG_UI_HBOX_LAST = "//*[@class='cke_dialog_ui_hbox_last']";
    public static final String GWT_HTML_CLASS = "//div[contains(@class,'gwt-HTML')]";
    public static final String TOC_RECITAL_LINK = "//*[text()='Recitals']";
    public static final String TOC_TABLE_TREE_GRID = "//table[@role='treegrid']";
    public static final String ANCESTOR = "//ancestor";
    public static final String FOLLOWING_SIBLING = "//following-sibling";
    public static final String COMPARISION_SECOND_PAGE = "//ancestor::div[contains(@class,'v-splitpanel-second-container')]";
    public static final String LEOS_CONTENT_NEW_CN = "[@class='leos-content-new-cn']";
    public static final String NOT_LEOS_CONTENT_NEW_CN = "[not(@class='leos-content-new-cn')]";
    public static final String LEOS_TOOLBAR_BUTTON = "//div[contains(@class,'leos-toolbar-button') and @role='button']";
    public static final String DOUBLE_COMPARISON_TOOL_BAR = "//*[@id='doubleComparisonToolbar']";
    public static final String LEOS_DOUBLE_COMPARE_ADDED_ORIGINAL = "[@class='leos-double-compare-added-original']";
    public static final String LEOS_DOUBLE_COMPARE_ADDED_INTERMEDIATE = "[@class='leos-double-compare-added-intermediate']";
    public static final String NOT_LEOS_DOUBLE_COMPARE_ADDED_INTERMEDIATE = "[not(@class='leos-double-compare-added-intermediate')]";
    public static final String LEOS_DOUBLE_COMPARE_REMOVED_ORIGINAL = "[@class='leos-double-compare-removed-original']";
    public static final String LEOS_DOUBLE_COMPARE_REMOVED_INTERMEDIATE = "[@class='leos-double-compare-removed-intermediate']";
    public static final String LEOS_DOUBLE_COMPARE_RETAINED_ORIGINAL = "[@class='leos-double-compare-retain-original']";
    public static final String VERSION_CARD = "//div[@id='versionCard']";
    public static final String COMPONENT_WRAP_CHECKBOX = "//ancestor::div[@class='component-wrap']//input[@type='checkbox']";
    public static final String VERSION_CARD_CHECKBOX = LegalActPage.ANCESTOR_VERSION_CARD + "//input[@type='checkbox']";
    public static final String LEOS_CONTENT_SOFT_REMOVED = "[@class='leos-content-soft-removed']";
    public static final String NOT_LEOS_CONTENT_SOFT_REMOVED = "[not(@class='leos-content-soft-removed')]";
    public static final String LEOS_CONTENT_REMOVED_CN = "[@class='leos-content-removed-cn']";
    public static final String LEOS_CONTENT_REMOVED = "[@class='leos-content-removed']";
    public static final String LEOS_CONTENT_NEW = "[@class='leos-content-new']";
    public static final String LEOS_CONTENT_SOFT_NEW = "[@class='leos-content-soft-new']";
    public static final String LEOS_ACCORDION_VERSIONS_PANE = "//*[text()='Versions pane']//ancestor::div[@id='leosAccordion']";
    public static final String VERSIONS_PANE = "//*[@id='versionCard']";
    public static final String V_LABEL_UNDEF_RECENT_CHANGES = "//*[contains(@class,'v-label-undef-w') and text()='Recent changes']";
    public static final String VERSION_ACTIONS_PNG = "//img[contains(@src,'version_actions.png')]";
    public static final String V_GRID_SCROLLER = "//div[@class='v-grid-scroller v-grid-scroller-vertical']";
    public static final String VERSION_CARD_ACTION_BLOCK = "//div[@id='versionCardActionBlock']";
    public static final String INPUT_TYPE_CHECK_BOX = "//input[@type='checkbox']";
    public static final String ANCESTOR_VERSION_CARD = "//ancestor::*[@id='versionCard']";
    public static final String V_SLOT_TITLE = "//*[@class='v-slot v-slot-title']";
}

