package europa.edit.pages;

import lombok.experimental.UtilityClass;
import org.openqa.selenium.By;

@UtilityClass
public class ProposalViewerPage {
    public static final By TITLE_ELEMENT = By.xpath("//*[contains(@class,'v-slot-doc-purpose')]//input");
    public static final By MILESTONE_ADD_ICON = By.xpath("//*[text()='Milestones']//ancestor::div[contains(@class,'ui-block-heading')]//span[contains(@class,'v-icon')]");
    public static final By MILESTONE_DROPDOWN_ICON = By.xpath("//td[@class='v-formlayout-contentcell']/div[@role='combobox']/div[@role='button']");
    public static final By MILESTONE_OPTIONS_SELECTED = By.xpath("//div[@role='dialog']/following-sibling::div[@role='list']/div[@class='popupContent']//table/tbody/tr/td[@role='listitem' and contains(@class,'selected')]/span");
    public static final By MILESTONE_TITLE_TEXTAREA = By.xpath("//*[text()='Add a milestone']/parent::div/following-sibling::div[1]//textarea");
    public static final By V_REQUIRED_FIELD_INDICATOR = By.xpath("//*[text()='Add a milestone']/parent::div/following-sibling::div[1]//span[@class='v-required-field-indicator']");
    public static final By MILESTONE_OPTION_OTHER = By.xpath("//div[@role='dialog']/following-sibling::div[@role='list']/div[@class='popupContent']//table/tbody/tr/td[@role='listitem']/span[text()='Other']");
    public static final By MILESTONE_OPTION_FOR_INTERSERVICE_CONSULTATION = By.xpath("//div[@role='dialog']/following-sibling::div[@role='list']/div[@class='popupContent']//table/tbody/tr/td[@role='listitem']/span[text()='For Interservice Consultation']");
    public static final By DELETE_BTN = By.xpath("//*[text()='Delete']");
    public static final By MANDATE_DELETION_CONFIRMATION_POPUP = By.xpath("//*[@class='v-window-header' and text()='Mandate deletion: confirmation']");
    public static final By CONFIRM_POPUP_DELETE_BTN = By.xpath("//*[@class='v-window-contents']//span[text()='Delete']");
    public static final By PROPOSAL_DELETION_CONFIRMATION_POPUP = By.xpath("//*[@class='v-window-header' and text()='Proposal deletion: confirmation']");
    public static final By COVER_PAGE_OPEN_BUTTON = By.xpath("//*[contains(@class,'ui-block-caption') and text()='Cover Page']//ancestor::div[contains(@class,'v-verticallayout-ui-block')]//*[@class='v-button-caption' and text()='Open']");
    public static final By LEGAL_ACT_OPEN_BUTTON = By.xpath("(//*[text()='Legal Act']//ancestor::div[contains(@class,'ui-block ')]//child::div[contains(@class,'v-slot-ui-block-content')])[1]//*[text()='Open']");
    public static final By EXP_MEMO_OPEN_BUTTON = By.xpath("(//*[text()='Explanatory Memorandum']//ancestor::div[contains(@class,'ui-block ')]//child::div[contains(@class,'v-slot-ui-block-content')])[1]//*[text()='Open']");
    public static final By ADD_NEW_EXPLANATORY_BUTTON = By.xpath("//*[text()='Council Explanatory']//parent::div[@class='v-slot']//following-sibling::div//span[contains(@class,'Vaadin-Icons')]");
    public static final By COUNCIL_EXPLANATORY_TABLE_TBODY_TR = By.xpath("//*[contains(@class,'v-slot-explanatory-block')]//tbody/tr");
    public static final By COUNCIL_EXPLANATORY_CONFIRM_PAGE_CANCEL_BUTTON = By.xpath("//*[text()='Cancel']");
    public static final By COUNCIL_EXPLANATORY_CONFIRM_PAGE_DELETE_BUTTON = By.xpath("//*[@id='confirmdialog-ok-button']//*[text()='Delete']");
    public static final By CLOSE_BUTTON = By.xpath("//*[text()='Close']");
    public static final By ADD_A_MILESTONE_TEXT = By.xpath("//div[text()='Add a milestone']");
    public static final By COLLABORATORS_ADD_BUTTON = By.xpath("//*[text()='Collaborators']//ancestor::div[contains(@class,'ui-block-heading')]//*[contains(@class,'icon-only-add-button')]");
    public static final By ANNEXES_ADD_BUTTON = By.xpath("//*[text()='Annexes']//ancestor::div[contains(@class,'ui-block-heading')]//*[contains(@class,'icon-only-create-annex-button')]");
    public static final By CLOSE_BTN = By.xpath("//*[text()='Close']");
    public static final By PROPOSALVIEWERTEXT = By.xpath("//*[text()='Proposal Viewer']");
    public static final By OVERVIEWTEXT = By.xpath("//*[text()='Overview']");
    public static final By EXPORT_BTN = By.xpath("//*[text()='Export']");
    public static final By DOWNLOAD_BTN = By.xpath("//*[text()='Download']");
    public static final By EXPLN_MEMORANDUM_TEXT = By.xpath("//div[text()='Explanatory Memorandum']");
    public static final By COVER_PAGE_BLOCK = By.xpath("//*[contains(@class,'ui-block-heading')]//*[text()='Cover Page']");
    public static final By LEGALACTTEXT = By.xpath("//div[text()='Legal Act']");
    public static final By ANNEXESTEXT = By.xpath("//div[text()='Annexes']");
    public static final By COLLABORATORSTEXT = By.xpath("//div[text()='Collaborators']");
    public static final By MILESTONESTEXT = By.xpath("//div[text()='Milestones']");
    public static final By HOME_BTN = By.xpath("//div[@class='home-icon']");
    public static final By CONFIRM_POPUP_CANCEL_BTN = By.xpath("//*[@class='v-window-contents']//span[text()='Cancel']");
    public static final By MILESTONE_ACTIONS_MENU_ITEM = By.xpath("//*[contains(@src,'version_actions.png')]");
    public static final By MILESTONE_SEND_COPY_FOR_CONTRIBUTION = By.xpath("//*[text()='Send a copy for contribution']");
    public static final By SHARE_MILESTONE_TARGET_USER_INPUT = By.xpath("//*[text()='Target user']/ancestor::tr//input");
    public static final By SEND_FOR_CONTRIBUTION_BUTTON = By.xpath("//*[text()='Send for contribution']//ancestor::div[@role='button']");
    public static final By SEND_FOR_CONTRIBUTION_DISABLED_BUTTON = By.xpath("//*[text()='Send for contribution']//ancestor::div[@role='button' and @aria-disabled='true']");
    public static final By SEND_COPY_MILESTONE_CONTRIBUTION_CANCEL_BUTTON = By.xpath("//*[text()='Send a copy of the milestone for contribution']//ancestor::div[@class='popupContent']//*[text()='Cancel']");
    public static final By CLONED_LABELS = By.xpath("//*[contains(@class,'v-label-cloned-labels')]");
    public static final By PROPOSAL_DOWNLOAD_MESSAGE = By.xpath("//*[@class='v-Notification-description' and text()='Proposal downloaded']");
    public static final By CREATE_MILESTONE_BUTTON = By.xpath("//*[text()='Create milestone']");
    public static final By VIEW_BUTTON_HAMBURGER_MENU = By.xpath("//*[contains(@class,'leos-actions-milestone-menu')]//span[text()='View']");
    public static final By CONFIRMATION_DIALOG_WINDOW_CREAT_CONTRIBUTION_MILESTONE = By.xpath("//*[@id='confirmdialog-window']//*[text()='Create contribution milestone']");
    public static final By CONFIRMATION_DIALOG_OK_BUTTON = By.cssSelector("#confirmdialog-ok-button");
    public static final By MILESTONE_BLOCK_TABLE_BODY = By.cssSelector(".milestone-block table tbody");
    public static final By LEOS_ACTIONS_MILESTONE_MENU = By.cssSelector(".leos-actions-milestone-menu");
    public static final By CONFIRMATION_DIALOG_WINDOW = By.cssSelector("#confirmdialog-window");
    public static final By DOC_STAGE = By.cssSelector(".doc-stage");
    public static final By DOC_TYPE = By.cssSelector(".doc-type");
    public static final By LEOS_ACTIONS_SUB_MENU_ITEM = By.cssSelector(".leos-actions-sub-menu-item.leos-actions-sub-menu-item");
    public static final String MILESTONE_ACTIONS_MENU_ITEM_CAPTION = "//*[@class='v-menubar-popup']//span[@class='v-menubar-menuitem-caption']";
    public static final String GWT_HTML = "//div[contains(@class,'gwt-HTML')]";
    public static final String V_BUTTON_CAPTION = "//span[contains(@class,'v-button-caption')]";
    public static final String MILESTONE_TABLE_TBODY_TR = "//table[@role='treegrid']//tbody/tr";
    public static final String MILESTONE_DROPDOWN_LIST_TR = "//div[@role='dialog']/following-sibling::div[@role='list']/div[@class='popupContent']//table/tbody/tr";
    public static final String MILESTONE_DROPDOWN_LIST_TD_SPAN = "//td[@role='listitem']/span";
    public static final String COUNCIL_EXPLANATORY_TABLE_THEAD_TR_TH = "//*[contains(@class,'v-slot-explanatory-block')]//thead/tr/th";
    public static final String COUNCIL_EXPLANATORY_TABLE_TBODY_TR_STRING = "//*[contains(@class,'v-slot-explanatory-block')]//tbody/tr";
    public static final String ANNEX_BLOCK = "//*[contains(@class,'v-slot-annex-block')]";
    public static final String ANNEX_TITLE_INPUT = "//input[@placeholder='Enter annex title']";
    public static final String TITLE_SAVE_BTN = "//div[contains(@class,'save-btn')]";
    public static final String TITLE_CANCEL_BTN = "//div[contains(@class,'cancel-btn')]";
    public static final String FONTAWESOME = "//span[contains(@class,'FontAwesome')]";
    public static final String DELETE_BUTTON_NOT_DISABLED = "//div[contains(@class,' delete-button') and not(contains(@class,' v-disabled'))]";
    public static final String ROLE_BUTTON = "//div[@role='button']";
    public static final String OPEN_TEXT = "//*[text()='Open']";
    public static final String ICON_ONLY_DELETE_BUTTON = "//*[contains(@class,'icon-only-delete-button')]";
    public static final String INPUT = "//input";
    public static final String SAVE_BUTTON = "//div[contains(@class,'save-btn') and @role='button']";
    public static final String CANCEL_BUTTON = "//div[contains(@class,'cancel-btn') and @role='button']";
    public static final String ECONSILIUM_TABLE_TBODY_TR = "//table[@role='grid']//tbody/tr";
    public static final String COUNCIL_EXPLANATORY_TR_OPEN_BUTTON = ".explanatory-block table tbody tr:nth-child(%s) td div.open-button";
}
