#Author: Satyabrata Das
#Keywords Summary : Testing for different functionalities in Explanatory Memorendum Page in CN instance of Edit Application
@ExplanatoryMemorendumPageRegressionScenariosEditCouncil
Feature: Explanatory Memorendum Page Regression Features in Edit Council

  Background:
    Given navigate to "Council" edit application
    When enter username "user.support.1.name" and password "user.support.1.pwd"
    Then  navigate to Repository Browser page

  @basicExpMemoScenario
  Scenario: LEOS-4146 CN Edition of elements - Browse Exp Memo Part
    When click on "Create mandate" button
    Then upload screen is showing with "Create new mandate - Upload a leg file (1/2)" page
    When upload a leg file for creating mandate from location "council\PROP_ACT_4908055602317520447_UG.leg"
    Then file name should be displayed in upload window
    And  valid icon should be displayed in upload window
    When click on "Next" button
    Then upload screen is showing with Create new mandate - Draft metadata page
    When click on "Create" button
    Then navigate to Repository Browser page
    When click on the open button of first proposal/mandate
    Then OverView screen is displayed
    When click on open button for explanatory memorandum
    Then explanatory memorandum page is displayed
    And  navigation pane is displayed
    And  toc editing button is not displayed
    And  explanatory memorandum content is displayed
    When click on actions hamburger icon
    Then below options are displayed
      | Versions                               |
      | View                                   |
      | See user guidance                      |
      | See navigation pane                    |
    When click on "See user guidance" option
    Then below sentences are present for user guidance
      | [The standard guidance of an Explanatory Memorandum should be as follows. In principle it should not exceed 15 pages (in particularly complex cases a longer text may be justified). The language should be clear and simple, ensuring reader-friendliness for non-experts. All of the following elements are mandatory unless otherwise stated].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | [Describe the reasons behind the proposal and the problem(s) it is expected to tackle. State if this is an initiative within the Regulatory Fitness Programme (REFIT). State any relevant institutional background of the proposal.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | [Mention relevant existing policy provisions in the policy area and clarify how the proposal relates to them (e.g. differences, complementarity).]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | [Mention links with other key Union policies.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | [Explain the choice of legal basis of the proposal. Where several feasible options seem to exist, justify the choice on the basis of objective criteria.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | [Explain the Union dimension of the problem. Describe why the objectives cannot be adequately achieved by the Member States (necessity test). Explain why action at Union level would be more effective than action at national level and outline the added value of action at Union level (effectiveness test).]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | [Explain the policy choices of the proposal and why they are considered proportionate (i.e. not going beyond what it necessary to achieve the objectives). Explain why it is considered the most suitable measure for achieving the objective. Where an Impact Assessment accompanies the proposal, reference should be made to the appropriate parts which discuss proportionality.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | [Where appropriate, explain the choice of the instrument.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | [If applicable, summarise results of any ex-post evaluations/fitness checks of existing legislation. Clarify the link to the problems identified in the proposal.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | [Describe the consultations carried out, summarise the input received, as well as how this was taken into account in the proposal. Where appropriate, explain where the Commission's views diverge and why.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | [Where relevant, a short summary on the external expertise on which the Commission has relied (approach, range, advice received and used, publicly available information).]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | [For proposals not supported by an Impact Assessment, please explain the reasons why no Impact Assessment was carried out with reference to the accompanying roadmap and the Guidelines on Better Regulation.]\n[For proposals supported by an Impact Assessment, please provide links to the summary sheet and to the positive opinion of the Regulatory Scrutiny Board. In the absence of a positive opinion from the Board, please provide justification for proceeding with the initiative.]\n[Explain which policy alternatives were examined, compare them and explain why the final proposal was considered to be the best policy choice.]\n[Describe the main economic, social and environmental impacts of the preferred option, who would be affected and how. Include quantitative estimates of benefits and costs wherever possible and, if not available, explain why.]\n[If the final policy proposal deviates from the options assessed in the impact assessment, clarify the differences in approach and their likely impact.] |
      | [For proposals linked to REFIT and aimed at reducing regulatory burdens, provide, wherever possible, quantified estimates of the intended burden reduction.\n[Outline whether the proposal exempts micro-enterprises and the reasons why if it does not do so.]\n[Explain how the proposal minimizes compliance costs for SMEs (via lighter regimes, mitigating measures, etc.) and other stakeholders, as well as any positive or negative impact on sectoral EU competitiveness or international trade.]\n[Explain how the proposal is consistent with the "Digital Check" and is internet ready and appropriate for both the physical and digital environment (please see Better Regulation guideline and tool on ICT impacts in the Better Regulation Toolbox for more information).]                                                                                                                                                                                                                                                      |
      | [If the proposal has consequences for the protection of fundamental rights, explain how fundamental rights obligations have been met.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | [Outline the budgetary implications of the initiative (if any) and, where appropriate, refer to the "financial statement" showing the budgetary implications and the human and administrative resources required.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | [Refer to the implementation planning associated with the measure, including the monitoring, evaluation and reporting framework set up to assist with its implementation and application and to report on its performance.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | [Explain if the proposal requires Explanatory Documents on the transposition and why.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    When click on actions hamburger icon
    And  click on "See user guidance" option
    Then user guidance is not present in the page
    When click on "1. - CONTEXT OF THE PROPOSAL" link in navigation pane
    Then page is redirected to "CONTEXT OF THE PROPOSAL"
    When click on annotation pop up button
    When select "CONTEXT OF THE PROPOSAL" in the page
    Then comment button is displayed
    Then highlight button is displayed
    When click on close button in explanatory memorandum page
    Then OverView screen is displayed
    And  close the browser